SearchModule.create(tag: 'OVER', display_name: 'Spelling Overrides (Bing/Google)')
SearchModule.create(tag: 'IMAG', display_name: 'Image Results (Bing)')
SearchModule.create(tag: 'BOOS', display_name: 'Best Bets: Text')
SearchModule.create(tag: 'BWEB', display_name: 'Web Results (Bing)')
SearchModule.create(tag: 'BSPEL', display_name: 'Spelling Suggestions (Bing/Google)')
SearchModule.create(tag: 'NEWS', display_name: 'RSS Feeds')
SearchModule.create(tag: 'AIDOC', display_name: 'Collections')
SearchModule.create(tag: 'BBG', display_name: 'Best Bets: Graphics')
SearchModule.create(tag: 'SREL', display_name: 'Related Searches')
SearchModule.create(tag: 'TWEET', display_name: 'Tweets')
SearchModule.create(tag: 'JOBS', display_name: 'Jobs')
SearchModule.create(tag: 'VIDS', display_name: 'Video Results (YouTube)')
SearchModule.create(tag: 'GWEB', display_name: 'Web Results (Google)')
SearchModule.create(tag: 'NIMAG', display_name: 'Image Results (MRSS)')
SearchModule.create(tag: 'SPEL', display_name: 'Spelling Suggestions (DigitalGov Search)')
SearchModule.create(tag: 'LOVER', display_name: 'Spelling Overrides (DigitalGov Search)')
SearchModule.create(tag: 'OASIS', display_name: 'Image Results (DigitalGov Search)')
SearchModule.create(tag: 'OSPEL', display_name: 'Spelling Suggestions (DigitalGov Search Images)')
SearchModule.create(tag: 'AWEB', display_name: 'Web Results Only (Azure)')
SearchModule.create(tag: 'FRDOC', display_name: 'Federal Register Documents')
SearchModule.create(tag: 'DECOR', display_name: 'Value-added Links for SEC Filings')
SearchModule.create(tag: 'MEDL', display_name: 'Health Topics')
SearchModule.create(tag: 'ISPEL', display_name: 'i14y Spelling Overrides')
SearchModule.create(tag: 'I14Y', display_name: 'i14y Documents')
SearchModule.create(tag: 'QRTD', display_name: 'Routed Queries')
SearchModule.create(tag: 'AIMAG', display_name: 'Image Results (Azure)')
SearchModule.create(tag: 'AZCI', display_name: 'Image Results (Azure)')
SearchModule.create(tag: 'AZCW', display_name: 'Web Results Composite (Azure)')
