version: '2'
# Work around CodeClimate's inability to use Rubocop's inherit_gem directive:
# https://github.com/codeclimate/codeclimate-rubocop/issues/71#issuecomment-635055223
prepare:
  fetch:
    - url: https://raw.githubusercontent.com/GSA/searchgov_style/main/.default.yml
      path: .rubocop-https---raw-githubusercontent-com-GSA-searchgov-style-main--default-yml
checks:
  method-lines:
    enabled: false
plugins:
  brakeman:
    enabled: true
    exclude_fingerprints:
    - 3ea88cadfeec23aca30866f2d32ba0c1ed4ce23728f7824a7dd405af6383f52a
    - 4dd7e3efa71bfd02a5a6c9158ec54f9ceef4d991a72b974fbaa7d89e931b631d
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
    - "spec/"
    config:
      languages:
      - ruby
      - javascript
  # ESLint is configured in .eslintrc and .eslintignore
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      extensions:
      - .js
      - .jsx
      - .ts
      - .tsx
  fixme:
    enabled: true
  # Rubocop is configured in .rubocop.yml
  rubocop:
    enabled: true
    channel: rubocop-1-39-0
exclude_patterns:
- config/
- db/
- features/
- script/
- vendor/
-  "**/vendor/**/*"
-  "**/vcr_cassettes/**/*"
- app/assets/images/
# These files were downloaded from https://designsystem.digital.gov/
- app/assets/stylesheets/uswds.css
- app/assets/stylesheets/uswds_override.css
