# Work around CodeClimate's inability to use Rubocop's inherit_gem directive:
# https://github.com/codeclimate/codeclimate-rubocop/issues/71#issuecomment-635055223
inherit_from:
  - https://raw.githubusercontent.com/GSA/searchgov_style/main/.default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    # All Instagram-related code is deprecated and will be removed
    - /**/**/instagram*

Style/LambdaCall:
  Exclude:
    # Exclude files relying on Jbuilder DSL
    # https://github.com/rubocop-hq/rubocop/issues/3402
    - 'app/models/elastic_data/*'
    - 'app/models/custom_index_queries/*'
    - 'app/models/logstash_queries/*'
    - 'app/models/watcher.rb'
    - 'lib/analytics_dsl.rb'
    - 'lib/watcher_dsl.rb'

Style/MethodCallWithArgsParentheses:
  IgnoreMacros: true
  IgnoredMethods: ['require']
  Exclude:
    # Exclude files relying on Jbuilder DSL
    - 'app/models/elastic_data/*'
    - 'app/models/custom_index_queries/*'
    - 'app/models/logstash_queries/*'
    - 'app/models/watcher.rb'
    - 'lib/analytics_dsl.rb'
    - 'lib/watcher_dsl.rb'

Style/NumericLiterals:
  Exclude:
    # Exclude files that tend to contain long, numeric ID's
    - /**/**/*twitter*
    - /**/**/*tweet*
    - spec/support/api_search_as_json_behavior.rb


