
version: 0.0
os: linux
# files:
#   - source: /
#     destination: /home/search/cicd_temp 

hooks:
  ApplicationStop:
    - location: cicd-scripts/cleanup_deployment.sh
      timeout: 300
      runas: search

  BeforeInstall:
    - location: cicd-scripts/fetch_env_vars.sh
      timeout: 300
      runas: search

  AfterInstall:
    - location: cicd-scripts/copy_non_fingerprinted_assets.sh
      timeout: 300
      runas: search


