
version: 0.2
env:
  parameter-store:
    APP_SERVER_ADDRESSES: "DEPLOY_SEARCHGOV_SERVER_ADDRESS"
    CRON_SERVER_ADDRESSES: "DEPLOY_CRON_SERVER_ADDRESSES"
    DEPLOYMENT_PATH: "DEPLOY_SEARCHGOV_DEPLOYMENT_PATH"
    RESQUE_SERVER_ADDRESSES: "DEPLOY_RESQUE_SERVER_ADDRESSES"
    RESQUE_WORKERS_COUNT: "DEPLOY_RESQUE_WORKERS_COUNT"
    SEARCHGOV_THREADS: "SEARCHGOV_THREADS"
    SEARCHGOV_WORKERS: "SEARCHGOV_WORKERS"
    SERVER_DEPLOYMENT_USER: "DEPLOY_SERVER_DEPLOYMENT_USER"

exported-variables:
  - APP_SERVER_ADDRESSES
  - DEPLOYMENT_PATH
  - RESQUE_SERVER_ADDRESSES
  - SEARCHGOV_THREADS
  - SEARCHGOV_WORKERS
  - SERVER_DEPLOYMENT_USER
  - SSH_KEY_PATH
  - SEARCH_ENV

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - export PATH="$HOME/.rbenv/bin:$PATH"
      - eval "$(rbenv init - true)"
      - ruby --version
      - gem --version
      
  pre_build:
    commands:
      - echo "Setting up SSH keys"
      - mkdir -p ~/.ssh
      - aws secretsmanager get-secret-value --secret-id $SEARCH_SECRETSMANAGER_KEY_SECRET_NAME --region $SEARCH_AWS_REGION --query 'SecretString' --output text > $SEARCH_ENV_EC2_KEY
      - chmod 600 ~/.ssh/id_rsa
      
  build:
    commands:
      - eval "$(ssh-agent -s)"
      - echo "deploying searchgov app with capistrano"
      - rm -rf vendor/bundle .bundle
      - bundle install --jobs=4 --retry=3
      - cap $SEARCH_ENV deploy
      - cap $SEARCH_ENV puma:config || true
      - cap $SEARCH_ENV puma:systemd:config || true
      - cap $SEARCH_ENV puma:systemd:enable || true
      - cap $SEARCH_ENV resque:restart || true
      - cap $SEARCH_ENV resque:scheduler:restart || true

artifacts:
  files:
    - '**/*'
