
version: 0.2
env:
  parameter-store:
    APP_SERVER_ADDRESSES: "DEPLOY_SEARCHGOV_SERVER_ADDRESS"
    CRON_SERVER_ADDRESSES: "DEPLOY_CRON_SERVER_ADDRESSES"
    DEPLOYMENT_PATH: "DEPLOY_SEARCHGOV_DEPLOYMENT_PATH"
    RESQUE_SERVER_ADDRESSES: "DEPLOY_RESQUE_SERVER_ADDRESSES"
    RESQUE_WORKERS_COUNT: "DEPLOY_RESQUE_WORKERS_COUNT"
    SEARCHGOV_THREADS: "SEARCHGOV_THREADS"
    SEARCHGOV_WORKERS: "SEARCHGOV_WORKERS"
    SERVER_DEPLOYMENT_USER: "DEPLOY_SERVER_DEPLOYMENT_USER"

    # shared deployment variables with subsequent stages - might not to export as this is the final stage
exported-variables:
    - APP_SERVER_ADDRESSES
    - DEPLOYMENT_PATH
    - RESQUE_SERVER_ADDRESSES
    - SEARCHGOV_THREADS
    - SEARCHGOV_WORKERS
    - SERVER_DEPLOYMENT_USER
    - SSH_KEY_PATH

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - export PATH="$HOME/.rbenv/bin:$PATH"
      - eval "$(rbenv init -)"
      
  pre_build:
    commands:
      - export CURRENT_LOCATION=$(pwd)  # would look something like this - /codebuild/output/src559980389/src - a temp dir created by codebuild
      - export SSH_KEY_PATH="${CURRENT_LOCATION}/${SEARCH_ENV_EC2_KEY}"
      - echo $SSH_KEY_PATH
      - rm -rf ~/.bundle || true
      - rm -rf vendor/bundle || true
      - aws secretsmanager get-secret-value --secret-id $SEARCH_SECRETSMANAGER_KEY_SECRET_NAME --region $SEARCH_AWS_REGION --query 'SecretString' --output text > $SEARCH_ENV_EC2_KEY
  
  build:
    commands:
      - export CURRENT_LOCATION=$(pwd)  # would look something like this - /codebuild/output/src559980389/src - a temp dir created by codebuild
      - export SSH_KEY_PATH="${CURRENT_LOCATION}/${SEARCH_ENV_EC2_KEY}"
      - echo "SSH Key Path in build: $SSH_KEY_PATH"
      - eval "$(ssh-agent -s)"
      - echo "deploying searchgov app with capistrano"
      - rm -rf vendor/bundle .bundle
      - bundle install --no-cache
      - aws secretsmanager get-secret-value --secret-id $SEARCH_SECRETSMANAGER_KEY_SECRET_NAME --region $SEARCH_AWS_REGION --query 'SecretString' --output text > $SEARCH_ENV_EC2_KEY
      - ls -la ~/.ssh/
      - chmod 600 ~/.ssh/id_rsa
      
  build:
    commands:
      - eval "$(ssh-agent -s)"
      - echo "deploying searchgov app with capistrano"
      - rm -rf vendor/bundle .bundle
      - bundle install --jobs=4 --retry=3
      - bundle exec cap $SEARCH_ENV deploy:check || true
      - bundle exec cap $SEARCH_ENV deploy
      - bundle exec cap $SEARCH_ENV puma:config || true
      - bundle exec cap $SEARCH_ENV puma:systemd:config || true
      - bundle exec cap $SEARCH_ENV puma:systemd:enable || true
      - bundle exec cap $SEARCH_ENV resque:restart || true
      - bundle execcap $SEARCH_ENV resque:scheduler:restart || true

artifacts:
  files:
    - '**/*'
