
version: 0.2

env:
  parameter-store:
    APP_SERVER_ADDRESSES: "DEPLOY_SEARCHGOV_SERVER_ADDRESS"
    CRON_SERVER_ADDRESSES: "DEPLOY_CRON_SERVER_ADDRESSES"
    DEPLOYMENT_PATH: "DEPLOY_SEARCHGOV_DEPLOYMENT_PATH"
    RESQUE_SERVER_ADDRESSES: "DEPLOY_RESQUE_SERVER_ADDRESSES"
    RESQUE_WORKERS_COUNT: "DEPLOY_RESQUE_WORKERS_COUNT"
    SEARCHGOV_THREADS: "SEARCHGOV_THREADS"
    SEARCHGOV_WORKERS: "SEARCHGOV_WORKERS"
    SERVER_DEPLOYMENT_USER: "DEPLOY_SERVER_DEPLOYMENT_USER"
    GITHUB_TOKEN: "DEPLOY_GITHUB_TOKEN"
    SEARCH_SECRETSMANAGER_KEY_SECRET_NAME: "SEARCH_SECRETSMANAGER_KEY_SECRET_NAME"
    SEARCH_AWS_REGION: "SEARCH_AWS_REGION"
    SEARCH_ENV_EC2_KEY: "SEARCH_ENV_EC2_KEY"

exported-variables:
  - APP_SERVER_ADDRESSES
  - DEPLOYMENT_PATH
  - RESQUE_SERVER_ADDRESSES
  - SEARCHGOV_THREADS
  - SEARCHGOV_WORKERS
  - SERVER_DEPLOYMENT_USER
  - SSH_KEY_PATH

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "=== Install phase ==="
      - export PATH="$HOME/.rbenv/bin:$PATH" || true
      - eval "$(rbenv init -)" || true
      - git config --global --add safe.directory '*'
      - git config --global advice.detachedHead false

  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      - rm -rf ~/.bundle vendor/bundle .bundle || true
      - echo "Fetching SSH key from Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id "$SEARCH_SECRETSMANAGER_KEY_SECRET_NAME" --region "$SEARCH_AWS_REGION" --query 'SecretString' --output text > "$SEARCH_ENV_EC2_KEY"
      - chmod 600 "$SEARCH_ENV_EC2_KEY"
      - export SSH_KEY_PATH="$(pwd)/$SEARCH_ENV_EC2_KEY"
      - echo "SSH_KEY_PATH=$SSH_KEY_PATH"

  build:
    commands:
      - echo "=== Build phase: bundle install ==="
      - bundle config set --local silence_root_warning true
      - bundle config set --local path 'ven
