# Be sure to use the -f flag to specify this compose file:
# docker compose -f docker-compose-m1.yml up --detach

version: '3.8'

services:
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch/data
    ports:
      - 9278:9200

  kibana6:
    image: docker.elastic.co/kibana/kibana:6.8.22
    ports:
      - 5668:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9268

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.8.1
    depends_on:
      - elasticsearch7
    ports:
      - 5678:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch7:9200

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - ./docker/my.cnf:/etc/my.cnf
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env/development/mysql

  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379

  tika:
    platform: linux/amd64
    image: apache/tika:1.24.1
    ports:
      - 9998:9998

volumes:
  db_data:
  es_6_data:
  es_7_data:
