export const moduleCode = {
  bestBetsGraphics: 'BBG',
  bestBetsText: 'BOOS',
  collections: 'AIDOC',
  federalRegisterDocuments: 'FRDOC',
  healthTopics: 'MEDL',
  images: 'IMAG',
  jobs: 'JOBS',
  relatedSearches: 'SREL',
  rssFeeds: 'NEWS',
  spellingOverridesBing: 'OVER',
  spellingOverridesSearch: 'LOVER',
  spellingSuggestionsBing: 'BSPEL',
  spellingSuggestionsImages: 'OSPEL',
  spellingSuggestionsSearch: 'SPEL',
  videos: 'VIDS',
  webNews: 'NEWS',
  webWeb: 'BWEB',
  webDocument: 'SRCH',
} as const;
