export const moduleCode = {
  bestBetsGraphics: 'BBG',
  bestBetsText: 'BOOS',
  collections: 'AIDOC',
  federalRegisterDocuments: 'FRDOC',
  healthTopics: 'MEDL',
  images: 'IMAG',
  jobs: 'JOBS',
  relatedSearches: 'SREL',
  rssFeeds: 'NEWS',
  spellingOverridesBing: 'OVER',
  spellingOverridesSearch: 'LOVER',
  spellingSuggestionsBing: 'BSPEL',
  spellingSuggestionsImages: 'OSPEL',
  spellingSuggestionsSearch: 'SPEL',
  spellingOverridesI14y: 'ISPEL',
  videos: 'VIDS',
  webI14y: 'I14Y',
  webNews: 'NEWS',
  webWeb: 'BWEB'
} as const;
