default: &DEFAULT
  options:
    open_timeout: 1
    timeout: 3

azure_default: &AZURE_DEFAULT
  <<: *DEFAULT
  adapter: :typhoeus

i14y_default: &I14Y_DEFAULT
  adapter: :typhoeus
  options:
    timeout: 0

development: &DEVELOPMENT
  <<: *DEFAULT
  adapter: :net_http_persistent

  azure_web_api:
    <<: *AZURE_DEFAULT
  azure_composite_api:
    <<: *AZURE_DEFAULT
  i14y:
    <<: *I14Y_DEFAULT

test:
  <<: *DEVELOPMENT
  i14y:
    <<: *I14Y_DEFAULT

azure_production: &AZURE_PROD
  options:
    open_timeout: 1 # http://stackoverflow.com/questions/7987584/curl-timeout-less-than-1000ms-always-fails
    timeout: 2
  adapter: :typhoeus

bing_v5_prod: &BING_V5_PROD
  options:
    open_timeout: 3 # http://stackoverflow.com/questions/7987584/curl-timeout-less-than-1000ms-always-fails
    timeout: 6
  adapter: :typhoeus

production: &PRODUCTION
  options:
    open_timeout: 0.5
    timeout: 2
  adapter: :net_http_persistent

  azure_web_api:
    <<: *AZURE_PROD
  azure_composite_api:
    <<: *AZURE_PROD
  bing_v5_api:
    <<: *BING_V5_PROD
  i14y:
    <<: *I14Y_DEFAULT
