default: &DEFAULT
  options:
    open_timeout: 1
    timeout: 3

development: &DEVELOPMENT
  <<: *DEFAULT
  adapter: :net_http_persistent

test:
  <<: *DEVELOPMENT

production: &PRODUCTION
  options:
    open_timeout: 0.5
    timeout: 2
  adapter: :net_http_persistent
