<%= Rails.env %>:
  app_name: <%= Rails.application.secrets.newrelic[:app_name] %>
  license_key: <%= Rails.application.secrets.newrelic[:license_key] %>
  log_level: <%= Rails.application.secrets.newrelic[:log_level] || 'info' %>
  monitor_mode: <%= Rails.application.secrets.newrelic[:enabled] ? 'true' : 'false' %>
  apdex_t: <%= Rails.application.secrets.newrelic[:apdex_t] || 0.5 %>
  capture_params: false
  disable_curb: true
  backport_fast_active_record_connection_lookup: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    explain_enabled: true
    explain_threshold: 0.5
  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: ActionController::RoutingError
  common: &default_settings
    host: <%= Rails.application.secrets.newrelic[:endpoint] %>
