development:
  app_name: USA Search
  license_key: FILL_IN_LICENSE_KEY
  developer_mode: true
  monitor_mode: false
  log_level: info
  apdex_t: 0.5
  capture_params: false
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    explain_enabled: true
    explain_threshold: 0.5
  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: ActionController::RoutingError
