# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

# Specifies the `worker_timeout` threshold that Puma will use to wait before
# terminating a worker in development environments.
worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

# Comment out the port setting if you are using bind
# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
# port ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Use the bind directive to specify the address and port to listen on
bind "tcp://0.0.0.0:3000"

# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart

# In Puma cluster mode the rails_semantic_logger async appender thread does not
# survive the fork into workers, so request-level logs generated by workers were
# never flushed to disk -- only the master's boot messages appeared. Flush the
# master's queue before forking and reopen the appender in each worker so request
# logs reach shared/log/production.log (and CloudWatch).
before_fork do
  SemanticLogger.flush if defined?(SemanticLogger)
end

on_worker_boot do
  SemanticLogger.reopen if defined?(SemanticLogger)
end
