default: &DEFAULT
  namespace: oasis
  url: <%= ENV['REDIS_HOST'] || 'redis://localhost:6379' %>

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
