default: &DEFAULT
  namespace: oasis
  url: <%= ENV.fetch('REDIS_SYSTEM_URL', 'localhost:6379') %>

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
