default: &DEFAULT
  namespace: oasis
  url: <%= ENV.fetch('REDIS_SYSTEM_URL') %>
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] %>

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT
