default: &DEFAULT
  verify_peer: true
  cert_chain_file: <%= ENV['SSL_CERT_FILE'] || OpenSSL::X509::DEFAULT_CERT_FILE %>

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

production:
  <<: *DEFAULT
  # Workaround for "OpenSSL::X509::DEFAULT_CERT_FILE" pointing to a missing file in Ubuntu
  # https://github.com/actions/virtual-environments/issues/235
  cert_chain_file: '/etc/ssl/certs/ca-certificates.crt'
