class AddAutoGeneratedToBoostedContent < ActiveRecord::Migration
  def self.up
    add_column :boosted_contents, :auto_generated, :boolean, :null => false, :default => false
  end

  def self.down
    remove_column :boosted_contents, :auto_generated
  end
end
