class SeedApiWhitelist < ActiveRecord::Migration
  def up
    entries = %w(stateofnevada opm-demo census.test maine.gov tceq fb707f101 search.kentucky.gov pbgc hawaiistateportal samhsa-store revenue.ky.gov healthypeople education.ky.gov floodsmart chfs.ky.gov fw.ky.gov wh necourts corrections.ky.gov sos.ky.gov scottia kbn.ky.gov oregon ag.ky.gov cosd idahogov descanso kyhousing.org oregonwashingtonbureauoflandmanag nimh-catalog-prod nysdhses kdla.ky.gov oshrc aflink usstratcom usgs_ecosystems krec.ky.gov armyrotc usccr cpe.ky.gov pharmacy.ky.gov kyret.ky.gov www.drugabuse.gov kbhc.ky.gov drought ncd kyae.ky.gov public wpb.org kyem.ky.gov agents-floodsmart ovr.ky.gov justice.ky.gov u.s.armycorpsofengineersheadquart courts.ky.gov elect.ky.gov franklincounty.ky.gov mdm goshrp2 afrc ninds-catalog drive.ky.gov nasa-appel goals.performance.gov cartercounty.ky.gov pt.ky.gov djj.ky.gov mvc.ky.gov aetc sbir usda-ams mi-som kref.ky.gov webstercountyclerk.ky.gov robins hartcounty.ky.gov afsoc logancounty.ky.gov ols_app afpw_travis afpw_offutt stopfraud.gov peterson mcleancounty.ky.gov afpw_afhra hill toddcounty.ky.gov waynecounty.ky.gov morgancounty.ky.gov mcbbutler gravescounty.ky.gov wrightpatt nps luke afpw_106rqw westover torch hickmancounty.ky.gov vandenberg macdillairforcebase beaverdam.ky.gov afpw_afcec usda-nfc triggcountyclerk.ky.gov march losangeles beale simpsoncountyclerk.ky.gov performance.gov kcma.ky.gov davismonthan bathcounty.ky.gov afpw_123aw yokota sheppard riley princeton.ky.gov nellis letchercounty.ky.gov kwcfc.ky.gov hartford.ky.gov goodfellow cca.ky.gov afmc usafacademy patrick niagarafalls netcents mountainhome langley keesler kbefd.ky.gov incirlik elliottcounty.ky.gov eglin dobbins columbus boa.ky.gov afpw_maxwell afpw_charleston afpw_afpc afpw_79mdw usace_pubs safie pittsburgh ncdenr mildenhall malmstrom magoffincountyclerk.ky.gov lrn jbsa housing holloman hickam cannon buckley afpw_mcguire afpw_eads afpw_afro afpw_176wg afbmt 927arw tyndall tecom pa-firstnet ome.ky.gov neworleans_district mortonsgap.ky.gov moody mobile_district lajes hurlburt hanscom hancockfield eielson charleston_district bluegrasssouth.ky.gov angrc afpw_sg afpw_scott afpw_grandforks afpw_andrews afpw_173fw afpw_169fw afpw_167aw 9af 59mdw vance usafe seymourjohnson schriever rghs ramstein osd_comptroller osd_cio_nii museum misawa mcbhawaii littlerock lesliecountyclerk.ky.gov laughlin lakenheath kirtland justice.gov icollege_ndu homestead grissom elmendorf dpclo detroit_district claycounty.ky.gov bmtflightphotos blog.governor.ky.gov barracks all-marines afpw_mcconnell afpw_creech afpw_ang afpw_afsc afpw_162fw afpw_153aw afpw_142fw afpw_134arw afpw_127wg afpw_121arw afpw_110aw afosi 940wg 501csw 3rdmaw)
    entries.each {|handle| WhitelistedV1ApiHandle.create(handle: handle)}
  end

  def down
  end
end
