Feature: Search.USA.gov Best Bets: Text
  In order to boost specific content to the top of search results
  As an affiliate admin
  I want to manage Search.USA.gov Best Bets: Text

  Scenario: Visiting Boosted Contents index page
    Given the following Boosted Content entries exist:
      | title                                                                                                      | url                               | description          | keywords | autogenerated | locale | status   | publish_start_on | publish_end_on |
      | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at tincidunt erat. Sed sit amet massa massa. | http://www.hello.gov/there.htm    | fire island          | lens     | false         | en     | active   | 08/30/2011       | 08/30/2020     |
      | fresnel lens                                                                                               | http://www.hello.gov/fresnels.htm | fresnels description |          | true          | es     | inactive | 09/01/2011       |                |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the admin home page
    And I follow "Best Bets: Text"
    Then I should see the following breadcrumbs: USASearch > Search.USA.gov > Admin Center > Search.USA.gov Best Bets: Text
    And I should see "Search.USA.gov Best Bets: Text" in the page header
    And I should see "Displaying all 2 Best Bets: Text entries"
    And I should see 2 Boosted Content Entries
    And I should see "Add new text"
    And I should see the following table rows:
      | Title                          | URL                        | Publish Start | Status   |
      | fresnel lens                   | www.hello.gov/fresnels.htm | 09/01/2011    | Inactive |
      | Lorem ipsum dolor sit amet,... | www.hello.gov/there.htm    | 08/30/2011    | Active   |
    When I follow "fresnel lens"
    Then I should see "fresnel lens"
    And I should see "http://www.hello.gov/fresnels.htm"
    And I should see "fresnels description"
    And I should see "Spanish"
    And I should see "Inactive"
    And I should see "Yes"

    When there are 30 Boosted Content entries exist:
      | locale | status |
      | en     | active |
    And I go to the boosted contents admin page
    And I should see "Displaying Best Bets: Text entries 1 - 20 of 32 in total"
    And I should see 20 Boosted Content Entries
    When I follow "Next"
    Then I should see "Displaying Best Bets: Text entries 21 - 32 of 32 in total"
    And I should see "title 10"

  Scenario: Create a new Boosted Content entry
    Given I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    Then I should see "Search.USA.gov has no Best Bets: Text"
    When I follow "Add new text"
    Then I should see the following breadcrumbs: USASearch > Search.USA.gov > Admin Center > Search.USA.gov Best Bets: Text > Add a new Best Bets: Text
    And I should see "Add a new Best Bets: Text" in the page header
    And the "Publish start date" field should contain today's date
    And I fill in "Title" with "Test"
    And I fill in "URL" with "http://www.test.gov"
    And I fill in "Description" with "Test Description"
    And I fill in "Keywords" with "unrelated, terms"
    And I select "English" from "Locale*"
    And I select "Active" from "Status*"
    And I press "Add"
    Then I should see "Best Bets: Text entry successfully added"
    And I should see the following breadcrumbs: USASearch > Search.USA.gov > Admin Center > Search.USA.gov Best Bets: Text > Best Bets: Text entry
    And I should see "Best Bets: Text entry" in the page header
    And I should see "Test"
    And I should see "http://www.test.gov"
    And I should see "Test Description"
    And I should see "English"
    And I should see "Active"
    And I should see "No"
    And I should see boosted content keyword "unrelated"
    And I should see boosted content keyword "terms"
    And I should not see "unrelated, terms"
    When I follow "Add another Best Bets: Text"
    Then I should see "Add a new Best Bets: Text" in the page header
    When I follow "Cancel"
    Then I should see "Displaying 1 Best Bets: Text entry"

  Scenario: Create Boosted Content with URL without http:// prefix
    Given I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Add new text"
    And I fill in "Title" with "Test"
    And I fill in "URL" with "www.test.gov"
    And I fill in "Description" with "Test Description"
    And I select "English" from "Locale*"
    And I select "Active" from "Status*"
    And I press "Add"
    Then I should see "Best Bets: Text entry successfully added"
    And I should see "http://www.test.gov"

  Scenario: Validating Boosted Content on create
    Given the following Boosted Content entries exist:
      | title        | url                            | description | keywords | autogenerated | status |
      | fresnel lens | http://www.hello.gov/there.htm | fire island | lens     | true          | active |
    Given I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Add new text"
    And I fill in the following:
      | Publish start date | 07/01/2012                              |
      | Publish end date   | 07/01/2011                              |
    And I press "Add"
    Then I should see "Title can't be blank"
    And I should see "URL can't be blank"
    And I should see "Description can't be blank"
    And I should see "Locale must be selected"
    And I should see "Status must be selected"
    And I should see "Publish end date can't be before publish start date"

    When I fill in "URL" with "http://www.hello.gov/there.htm"
    And I fill in "Publish start date" with ""
    And I press "Add"
    Then I should see "URL has already been boosted"
    And I should see "Publish start date can't be blank"

  Scenario: Edit a Boosted Content entry
    Given the following Boosted Content entries exist:
     | title            | url               | description       | keywords          |
     | a title          | http://a.url.gov  | A description     | unrelated, terms  |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Edit"
    Then I should see the following breadcrumbs: USASearch > Search.USA.gov > Admin Center > Search.USA.gov Best Bets: Text > Edit Best Bets: Text entry
    And I fill in "Title" with "new title"
    And I fill in "Description" with "new description"
    And I fill in "Keywords" with "bananas, apples, oranges"
    And I press "Update"
    Then I should see "Best Bets: Text entry successfully updated"
    And I should see "new title"
    And I should not see "a title"
    And I should see "http://a.url.gov"
    And I should see "new description"
    And I should not see "a description"
    And I should see boosted content keyword "banana"
    And I should see boosted content keyword "apples"
    And I should see boosted content keyword "oranges"
    And I should not see "unrelated, terms"
    When I follow "Edit"
    And I follow "Cancel"
    Then I should see "Best Bets: Text" in the page header

  Scenario: Edit a Boosted Content's URL without http:// prefix
    Given the following Boosted Content entries exist:
     | title            | url               | description       | keywords          |
     | a title          | http://a.url.gov  | A description     | unrelated, terms  |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Edit"
    Then the "URL" field should contain "http://a.url.gov"
    When I fill in "URL" with "b.url.gov"
    And I press "Update"
    Then I should see "Best Bets: Text entry successfully updated"
    And I should see "http://b.url.gov"

  Scenario: Validating Boosted Content on update
    Given the following Boosted Content entries exist:
     | title            | url               | description       | keywords          |
     | a title          | http://a.url.gov  | A description     | unrelated, terms  |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Edit"
    And I fill in "Title" with ""
    And I fill in "URL" with ""
    And I fill in "Description" with ""
    And I fill in "Publish start date" with ""
    And I select "Select a locale" from "Locale*"
    And I select "Select a status" from "Status*"
    When I press "Update"
    Then I should see "Title can't be blank"
    And I should see "URL can't be blank"
    And I should see "Description can't be blank"
    And I should see "Locale must be selected"
    And I should see "Status must be selected"
    And I should see "Publish start date can't be blank"

  Scenario: Deleting a boosted content
    Given the following Boosted Content entries exist:
      | title          | url                | description   | keywords         |
      | a title        | http://a.url.gov/1 | A description | unrelated, terms |
      | another title  | http://a.url.gov/2 | A description | unrelated, terms |
      | one more title | http://a.url.gov/3 | A description | unrelated, terms |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    Then I should see "Displaying all 3 Best Bets: Text entries"
    And I should see "a title"
    And I should see "another title"
    And I should see "one more title"
    When I press "Delete" on the 2nd boosted content entry
    Then I should see "Best Bets: Text entry successfully deleted"
    And I should see "Displaying all 2 Best Bets: Text entries"
    And I should see "a title"
    And I should see "one more title"

  Scenario: Uploading valid XML document
    Given I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Bulk upload"
    Then I should see the following breadcrumbs: USASearch > Search.USA.gov > Admin Center > Search.USA.gov Best Bets: Text > Bulk Upload Best Bets: Text
    And I should see "Bulk Upload Best Bets: Text" in the page header
    And I attach the file "features/support/boosted_content.xml" to "bulk_upload_file"
    And I press "Upload"
    Then I should see "Successful Bulk Import"
    And I should see "2 Best Bets: Text entries successfully created."

    When I go to the boosted contents admin page
    Then I should see "This is a listing about Texas"
    And I should see "Some other listing about hurricanes"

    When I follow "Bulk upload"
    And I attach the file "features/support/new_boosted_content.xml" to "bulk_upload_file"
    And I press "Upload"
    Then I should see "Successful Bulk Import"
    And I should see "2 Best Bets: Text entries successfully updated."
    When I go to the boosted contents admin page
    Then I should see "New results about Texas"
    And I should see "New results about hurricanes"

  Scenario: Uploading invalid XML document
    Given the following Boosted Content entries exist:
      | title               | url                     | description                               |
      | Our Emergency Page  | http://www.aff.gov/911  | Updated information on the emergency      |
      | FAQ Emergency Page  | http://www.aff.gov/faq  | More information on the emergency         |
      | Our Tourism Page    | http://www.aff.gov/tou  | Tourism information                       |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Bulk upload"
    And I attach the file "features/support/missing_title_boosted_content.xml" to "bulk_upload_file"
    And I press "Upload"
    Then I should see the following breadcrumbs: USASearch > Search.USA.gov > Admin Center > Search.USA.gov Best Bets: Text > Bulk Upload Best Bets: Text
    And I should see "Bulk Upload Best Bets: Text" in the page header
    And I should see "Your XML document could not be processed. Please check the format and try again."

    When I go to the homepage
    And I fill in "query" with "tourism"
    And I submit the search form
    Then I should see "Our Tourism Page" within "#boosted"

  Scenario: Uploading valid boosted CSV document
    Given I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Bulk upload"
    And I attach the file "features/support/boosted_content.csv" to "bulk_upload_file"
    And I press "Upload"
    Then I should see "Successful Bulk Import"
    Then I should see "2 Best Bets: Text entries successfully created."

    When I go to the boosted contents admin page
    Then I should see "This is a listing about Texas"
    And I should see "Some other listing about hurricanes"

    When I follow "Bulk upload"
    And I attach the file "features/support/new_boosted_content.csv" to "bulk_upload_file"
    And I press "Upload"
    Then I should see "Successful Bulk Import"
    And I should see "2 Best Bets: Text entries successfully updated."
    And I should see "New results about Texas"
    And I should see "New results about hurricanes"

  Scenario: Uploading invalid booster CSV document
    Given the following Boosted Content entries exist:
      | title               | url                     | description                               |
      | Our Emergency Page  | http://www.aff.gov/911  | Updated information on the emergency      |
      | FAQ Emergency Page  | http://www.aff.gov/faq  | More information on the emergency         |
      | Our Tourism Page    | http://www.aff.gov/tou  | Tourism information                       |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Bulk upload"
    And I attach the file "features/support/missing_title_boosted_content.csv" to "bulk_upload_file"
    And I press "Upload"
    Then I should see "Your CSV document could not be processed. Please check the format and try again."

    When I go to the homepage
    And I fill in "query" with "tourism"
    And I submit the search form
    Then I should see "Our Tourism Page" within "#boosted"

   Scenario: Uploading unsupported boosted content document
    Given the following Boosted Content entries exist:
      | title               | url                     | description                               |
      | Our Emergency Page  | http://www.aff.gov/911  | Updated information on the emergency      |
      | FAQ Emergency Page  | http://www.aff.gov/faq  | More information on the emergency         |
      | Our Tourism Page    | http://www.aff.gov/tou  | Tourism information                       |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the boosted contents admin page
    And I follow "Bulk upload"
    And I attach the file "features/support/cant_read_this.doc" to "bulk_upload_file"
    And I press "Upload"
    Then I should see "Your filename should have .xml, .csv or .txt extension"

  Scenario: Search user should see only active boosted contents within publish date range
    Given the following Boosted Content entries exist:
      | title                                | url                         | description                      | status   | publish_start_on | publish_end_on |
      | expired boosted content              | http://www.aff.gov/expired  | expired description              | active   | prev_month       | yesterday      |
      | future1 boosted content              | http://www.aff.gov/future1  | future1 description              | active   | tomorrow         | next_month     |
      | future2 boosted content              | http://www.aff.gov/future2  | future2 description              | active   | tomorrow         |                |
      | current boosted content              | http://www.aff.gov/current  | current description              | active   | today            | next_month     |
      | current but inactive boosted content | http://www.aff.gov/inactive | current but inactive description | inactive | today            |                |
    And I am logged in with email "affiliate_admin@fixtures.org" and password "admin"
    When I go to the homepage
    And I fill in "query" with "boosted"
    And I press "Search"
    Then I should see "current boosted content"
    And I should not see "current but inactive"
    When I fill in "query" with "expired"
    And I press "Search"
    Then I should not see "expired boosted content"
    When I fill in "query" with "future1"
    And I press "Search"
    Then I should not see "future1 boosted content"
    When I fill in "query" with "future2"
    And I press "Search"
    Then I should not see "future2 boosted content"

  Scenario: Search user should see boosted contents with higher relevancy on title
    Given the following Boosted Content entries exist:
      | title                     | url                         | description           | status | publish_start_on |
      | boosted content 1         | http://www.aff.gov/current1 | current description 1 | active | today            |
      | boosted content 2         | http://www.aff.gov/current2 | current description 2 | active | today            |
      | current boosted content 3 | http://www.aff.gov/current3 | description 3         | active | today            |
      | current boosted content 4 | http://www.aff.gov/current4 | description 4         | active | today            |
      | current boosted content 5 | http://www.aff.gov/current5 | description 5         | active | today            |
    When I go to the homepage
    And I fill in "query" with "current"
    And I press "Search"
    Then I should see "current boosted content 3" in the boosted contents section
    And I should see "current boosted content 4" in the boosted contents section
    And I should see "current boosted content 5" in the boosted contents section
    And I should not see "boosted content 1" in the boosted contents section
    And I should not see "boosted content 2" in the boosted contents section

  Scenario: Search user should see boosted contents with medium relevancy on description
    Given the following Boosted Content entries exist:
      | title             | url                         | description           | keywords | status | publish_start_on |
      | boosted content 1 | http://www.aff.gov/current1 | description 1         | current  | active | today            |
      | boosted content 2 | http://www.aff.gov/current2 | description 2         | current  | active | today            |
      | boosted content 3 | http://www.aff.gov/current3 | current description 3 | boosted  | active | today            |
      | boosted content 4 | http://www.aff.gov/current4 | current description 4 | boosted  | active | today            |
      | boosted content 5 | http://www.aff.gov/current5 | current description 5 | boosted  | active | today            |
    When I go to the homepage
    And I fill in "query" with "current"
    And I press "Search"
    Then I should see "boosted content 3" in the boosted contents section
    And I should see "boosted content 4" in the boosted contents section
    And I should see "boosted content 5" in the boosted contents section
    And I should not see "boosted content 1" in the boosted contents section
    And I should not see "boosted content 2" in the boosted contents section
