# This Dockerfile can be removed once system wide update is done with Ruby 3.0

FROM cimg/ruby:2.7.5-browsers

USER root

RUN apt-get update && apt-get install -y \
  default-mysql-client \
  libprotobuf-dev \
  protobuf-compiler

USER circleci
